kind: Deployment
apiVersion: apps/v1
metadata:
	name: redis
	namespace: {{ .Values.namespace }}
	labels:
		app: portlal
		service: redis
spec:
	replicas: 1
	selector:
		matchLabels:
			app: portlal
			service: redis
	template:
		metadata:
			labels:
				app: portlal
				service: redis
		spec:
			containers:
			- name: redis
				image: redis:alpine
				imagePullPolicy: IfNotPresent
				ports:
				- name: http
					containerPort: 6379
					protocol: TCP
				resources:
					limits:
						cpu: 100m
						memory: 128Mi
					requests:
						cpu: 100m
						memory: 128Mi
				volumeMounts:
				- name: redis-data
					mountPath: /data
			volumes:
			- name: redis-data
				emptyDir: {}

---

kind: Service
apiVersion: v1
metadata:
	name: redis
	namespace: {{ .Values.namespace }}
	labels:
		app: portlal
		service: redis
spec:
	selector:
		app: portlal
		service: redis
	ports:
	- name: http
		port: 6379
		targetPort: 6379
		protocol: TCP