kind: Deployment
apiVersion: apps/v1
metadata:
	name: seq
	namespace: {{ .Values.namespace }}
	labels:
		app: portal
		service: seq
spec:
	replicas: 1
	selector:
		matchLabels:
			app: portal
			service: seq
	template:
		metadata:
			labels:
				app: portal
				service: seq
		spec:
			container:
				- name: seq
				  image: datalust/seq:latest
					imagePullPolicy: IfNotPresent
				  ports:
					- name: http
						containerPort: 80
						protocol: TCP
				  env:
					- name: ACCEPT_EULA
					  value: "Y"
					- name: SEQ_LICENSE
						value: "http://{{ .Values.hostname }}/log/"
				  volumeMounts:
					- name: seq-data
					  mountPath: /data
			volumes:
				- name: seq-data
					emptyDir: {}

---

kind: Service
apiVersion: v1
metadata:
	name: seq
	namespace: {{ .Values.namespace }}
	labels:
		app: portal
		service: seq
spec:
	selector:
		app: portal
		service: seq
	ports:
		- name: web
			port: 80
			targetPort: seq-http

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
	name: seq
	namespace: {{ .Values.namespace }}
	labels:
		app: portal
		service: seq
spec:
	rules:
		- host: {{ .Values.hostname }}
			http:
				paths:
					- path: /log
						pathType: Prefix
						backend:
							service:
								name: seq
								port:
									name: web

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
	name: seq
	namespace: {{ .Values.namespace }}
	labels:
		app: portal
		service: seq
spec:
	rules:
		- host: {{ .Values.hostname }}
			http:
				paths:
					- path: /log
						pathType: Exact
						backend:
							service:
								name: seq
								port:
									name: web