receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55678
      http:
        endpoint: 0.0.0.0:4317
  redis:
    endpoint: redis:6379

processors:
  batch:

exporters:
  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans
  logging:
  elasticsearch:
    endpoint: "http://elasticsearch:9200"
    index: "otel"
    pipeline: "otel"
  prometheus:
    namespace: otel
    const_labels:
      environment: dev

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin, elasticsearch]
    logs:
      receivers: [redis]
      processors: [batch]
      exporters: [logging, elasticsearch]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
