global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
  - job_name: 'zipkin'
    static_configs:
      - targets: ['zipkin:9411']
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
  - job_name: 'logstash'
    static_configs:
      - targets: ['logstash:9600']
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
