@startuml SaoVietClassDiagram

skinparam linetype ortho
skinparam shadowing true

class Student {
	- Id: string
	- Fullname: string
	- Gender: bool
	- Address: string
	- Dob: string
	- Pod: string
	- Occupation: string
	- Social: JsonElement
	+ AddStudent(object)
	+ GetStudents(object)
    + GetStudentById(string)
    + FindByName(string)
	+ UpdateStudent(object)
	+ DeleteStudent(string)
}

class CourseEnrollment {
	- ClassId: string
	- StudentId: string
	+ Add(object)
	+ Get(object)
    + Update(object)
    + Delete(string)
}

class Class {
	- Id: string
	- StartDate: string
	- EndDate: string
	- Fee: float
	- CourseId: string
	- BranchId: string
	+ AddClass(object)
	+ GetClasses(object)
	+ GetClassById(string)
    + UpdateClass(object)
    + DeleteClass(string)
}

class Course {
	- Id: string
	- Name: string
	- Description: string
	+ AddCourse(object)
	+ GetCourses()
	+ GetCourseById(string)
    + UpdateCourse(object)
    + DeleteCourse(string)
}

class Branch {
	- Id: string
	- Name: string
	- Address: string
	- Phone: string
	+ Branch()
	+ AddBranch(object)
	+ GetBranches()
	+ GetBranchById(string)
    + UpdateBranch(object)
    + DeleteBranch(string)
}

class ReceiptsExpenses {
	- Id: guid
	- Type: bool
	- Date: string
	- Amount: float
	- Note: string
	- BranchId: string
	+ AddReceiptsExpense(object)
	+ GetReceiptsExpenses(object)
	+ GetReceiptsExpenseById(string)
    + UpdateReceiptsExpense(object)
    + DeleteReceiptsExpense(string)
}

class Staff {
	- Id: string
	- Fullname: string
	- Dob: string
	- Address: string
	- Dsw: string
	- PositionId: int
	- BranchId: string
	- ManagerId: string
	+ AddStaff(object)
	+ GetStaffs(object)
    + GetStaffById(string)
    + FindByName(string)
	+ UpdateStaff(object)
	+ DeleteStaff(string)
}

class Position {
	- Id: int
	- Name: string
	+ AddPosition(object)
	+ GetPositions()
	+ GetPositionById(string)
    + UpdatePosition(object)
    + DeletePosition(string)
}

class StudentProgress {
	- Id: guid
	- LessonName: string
	- LessonContent: string
	- LessonDate: string
	- Status: string
	- LessonRating: int
	- TeacherId: string
	- ClassId: string
	- StudentId: string
	+ AddStudentProgress(object)
	+ GetStudentProgresses(object)
	+ GetStudentProgressById(string)
    + UpdateStudentProgress(object)
    + DeleteStudentProgress(string)
}

class CourseRegistraion {
	- Id: guid
	- Status: string
	- RegistrationDate: string
	- AppointmentDate: string
	- Fee: float
	- Discount: float
	- ClassId: string
	- StudentId: string
	- PaymentMethodId: int
	+ AddCourseRegistraion(object)
	+ GetCourseRegistraions(object)
	+ GetCourseRegistraionById(string)
    + UpdateCourseRegistraion(object)
    + DeleteCourseRegistraion(string)
}

class PaymentMethod {
	- Id: int
	- Name: string
	+ AddPaymentMethod(object)
	+ GetPaymentMethods()
	+ GetPaymentMethodById(string)
    + UpdatePaymentMethod(object)
    + DeletePaymentMethod(string)
}

class AspNetUsers {
	- Id: string
	- UserName: string
	- NormalizedUserName: string
	- Email: string
	- NormalizedEmail: string
	- EmailConfirmed: boolean
	- PasswordHash: string
	- SecurityStamp: string
	- ConcurrencyStamp: string
	- PhoneNumber: string
	- PhoneNumberConfirmed: boolean
	- TwoFactorEnabled: boolean
	- LockoutEnd: string
	- LockoutEnabled: boolean
	- AccessFailedCount: int
	- ImangeUrl: string
	- StudentId: string
	- StaffId: string
	+ Insert()
	+ Update()
	+ Delete()
	+ Get()
	+ IsExist()
}

class AspNetUserClaims {
	- Id: int
	- UserId: string
	- ClaimType: string
	- ClaimValue: string
	+ Insert()
	+ Update()
	+ Delete()
	+ Get()
	+ IsExist()
}

class AspNetUserLogins {
	- LoginProvider: string
	- ProviderKey: string
	- ProviderDisplayName: string
	- UserId: string
	+ Insert()
	+ Update()
	+ Delete()
	+ Get()
	+ IsExist()
}

class AspNetUserTokens {
	- UserId: string
	- LoginProvider: string
	- Name: string
	- Value: string
	+ Insert()
	+ Update()
	+ Delete()
	+ Get()
	+ IsExist()
}

class AspNetUserRoles {
	- UserId: string
	- RoleId: string
	+ Insert()
	+ Update()
	+ Delete()
	+ Get()
	+ IsExist()
}

class AspNetRoles {
	- Id: string
	- Name: string
	- NormalizedName: string
	- ConcurrencyStamp: string
	+ Insert()
	+ Update()
	+ Delete()
	+ Get()
	+ IsExist()
}

class AspNetRoleClaims {
	- Id: int
	- RoleId: string
	- ClaimType: string
	- ClaimValue: string
	+ Insert()
	+ Update()
	+ Delete()
	+ Get()
	+ IsExist()
}

hide empty members

class BranchManager
class Accountant
class Teacher
class Director
class Marketing

AspNetUsers "1" o-- "0..*" Student
AspNetUsers "1" o-- "0..*" Staff
AspNetUsers "1" o-- "0..*" AspNetUserClaims
AspNetUsers "1" o-- "0..*" AspNetUserLogins
AspNetUsers "1" *-- "0..*" AspNetUserTokens
AspNetUsers "1" *-- "0..*" AspNetUserRoles
AspNetRoles "1" <.. "0..*" AspNetUserRoles
AspNetRoles "1" o-- "0..*" AspNetRoleClaims
Student "1" *-- "0..*" CourseEnrollment
Class "1" <.. "0..*" CourseEnrollment
Class "1" o-- "0..*" Course
CourseEnrollment "1" o-- "0..*" StudentProgress
CourseEnrollment "1" o-- "0..*" CourseRegistraion
CourseRegistraion "1" o-- "0..*" PaymentMethod
Branch "1" o-- "0..*" Class
Branch "1" o-- "0..*" ReceiptsExpenses
Branch "1" o-- "0..*" Staff
Staff "1" <.. "0..*" Staff
Staff "1" o-- "0..*" Position
Staff "1" o-- "0..*" StudentProgress
Staff <|-down- BranchManager
Staff <|-down- Accountant
Staff <|-down- Teacher
Staff <|-down- Director
Staff <|-down- Marketing

@enduml