kind: Deployment
apiVersion: apps/v1
metadata:
	name: zipkin
	namespace: {{ .Values.namespace }}
	labels:
		app: portal
		service: zipkin
spec:
	replicas: 1
	selector:
		matchLabels:
			app: portal
			service: zipkin
	template:
		metadata:
			labels:
				app: portal
				service: zipkin
		spec:
			container:
				- name: zipkin
				  image: openzipkin/zipkin
					imagePullPolicy: IfNotPresent
				  ports:
					- containerPort: 9411
					  name: zipkin
						potocol: TCP
					requests:
						cpu: 100m
						memory: 256Mi
					limits:
						cpu: 100m
						memory: 256Mi

---

kind: Service
apiVersion: v1
metadata:
	name: zipkin
	namespace: {{ .Values.namespace }}
	labels:
		app: portal
		service: zipkin
spec:
	selector:
		app: portal
		service: zipkin
	ports:
		- name: zipkin
		  port: 9411
		  targetPort: 9411