@controller=Student

# Get all students
GET {{base_url}}/{{controller}}
Authorization: Bearer {{bearer_token}}

###

@id=NXN0020802
GET {{base_url}}/{{controller}}/{{id}}
Authorization: Bearer {{bearer_token}}

###

POST {{base_url}}/{{controller}}
Authorization: Bearer {{bearer_token}}
Content-Type: application/json

{
  "studentId": "NDA00160189",
  "fullname": "Nguyễn Đình Ánh",
  "gender": true,
  "address": "Biên Hòa, Đồng Nai",
  "dob": "16/01/1989",
  "pod": "Hà Tĩnh",
  "occupation": "Giảng viên Đại học",
  "socialNetwork": "",
}

###

DELETE {{base_url}}/{{controller}}/{{id}}
Authorization: Bearer {{bearer_token}}