@controller=PaymentMethod

# Get all payment methods
GET {{base_url}}/{{controller}}
Authorization: Bearer {{bearer_token}}

###

# Find payment method by id
@id=1
GET {{base_url}}/{{controller}}/{{id}}
Authorization: Bearer {{bearer_token}}

###

# Add new payment method
POST {{base_url}}/{{controller}}
Authorization: Bearer {{bearer_token}}
Content-Type: application/json

{
	"Name": "Tiền mặt"
}

###

# Delete payment method by id
DELETE {{base_url}}/{{controller}}/{{id}}
Authorization: Bearer {{bearer_token}}

###

# Update payment method
PUT {{base_url}}/{{controller}}
Authorization: Bearer {{bearer_token}}
Content-Type: application/json

{
	"Id": 1,
	"Name": "Tiền mặt"
}