name: Stale Issue Bot

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

jobs:
  stale-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Stale Issue Bot
        uses: peter-evans/stale@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: |
            This issue has been automatically marked as stale because it has not had
            recent activity. It will be closed if no further activity occurs. Thank you
            for your contributions.
          stale-issue-label: wontfix
          days-before-stale: 60
          days-before-close: 7
          exempt-issue-labels: 'pinned,security'
